version: '3.0'
services:
    wc-rpi:
        image: wc-rpi:1.0.0
        privileged: true
        hostname: ubuntu
        network_mode: host
        environment:
         - DISPLAY=${DISPLAY}
        volumes:
         # give authority and camera for gui app
         - /tmp/.X11-unix:/tmp/.X11-unix
         - $HOME/.Xauthority:/home/hero/.Xauthority:ro
         - /dev/video0:/dev/video0
         - ./:/home/hero/data
