version: '3.0'
services:
    wc-rpi:
        image: wc-rpi:latest
        network_mode: "host"
        privileged: true
        environment:
         - DISPLAY=$DISPLAY
        volumes:
         - /dev/video0:/dev/video0
         - /tmp/.X11-unix:/tmp/.X11-unix
         - ./:/home/hero/data
