version: '3.0'
services:
    wc-rpi:
        image: wc-rpi-clean:1.0.0
        privileged: true
        tty: true
        stdin_open: true
        hostname: ubuntu
        network_mode: host
        environment:
         - DISPLAY=${DISPLAY}
         - QT_X11_NO_MITSHM=1
        volumes:
         # give authority and camera for gui app
         - /tmp/.X11-unix:/tmp/.X11-unix:rw
         - $HOME/.Xauthority:/home/hero/.Xauthority:rw
         - ./:/home/hero/data
         - /dev/video0:/dev/video0
         - /dev/video1:/dev/video1
         - /dev/video2:/dev/video2
         - /dev/video3:/dev/video3
         - /dev/video4:/dev/video4
         - /dev/video5:/dev/video5
